PREFIX : <http://univie.ac.at/~a7901955/contents/>
PREFIX s: <https://univie.ac.at/~a7901955/schema/>
PREFIX rdf: <https://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# Welche moeglichen alternativen Bezeichnungen gibt es fuer einen LV-Termin, bzw. aus welchen Teilkonzepten setzt sich dieser zusammen?

# Die Fragestellung nach alternativen Bezeichnungen ist bei den vorliegenden Daten nicht sinnvoll, 
# da Termine keine Bezeichnungen haben, sondern nur die hierarchisch übergeordneten Elemente LV, Modul, etc.

# Die Frage aus welchen Begriffen ein Termin besteht wird mit einer Schemaabfrage gelöst:

SELECT *
FROM <base1_ontology.ttl>
WHERE {
  ?property a rdf:Property;
            rdfs:domain s:Appointment .
}