PREFIX : <http://univie.ac.at/~a7901955/contents/>
PREFIX s: <https://univie.ac.at/~a7901955/schema/>
PREFIX dc: <https://purl.org/dc/terms/>

SELECT ?x, ?y
FROM <quelle1.ttl>
WHERE {
    ?x dc:title ?y .
}

