PREFIX : <http://univie.ac.at/~a7901955/contents/>
PREFIX s: <https://univie.ac.at/~a7901955/schema/>
PREFIX dc: <https://purl.org/dc/terms/>
PREFIX rdf: <https://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

# + Ergebnis mit roqet, leer mit ARQ

SELECT ?appointment ?start 
FROM <x.ttl>
WHERE {
  ?appointment s:start ?start .
  FILTER ( ?start >= "2015-05-31T12:00:00"^^xsd:datetime)
}

